// Generated by gencpp from file rovio/SrvResetToPoseResponse.msg
// DO NOT EDIT!


#ifndef ROVIO_MESSAGE_SRVRESETTOPOSERESPONSE_H
#define ROVIO_MESSAGE_SRVRESETTOPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace rovio
{
template <class ContainerAllocator>
struct SrvResetToPoseResponse_
{
  typedef SrvResetToPoseResponse_<ContainerAllocator> Type;

  SrvResetToPoseResponse_()
    : nothing()  {
    }
  SrvResetToPoseResponse_(const ContainerAllocator& _alloc)
    : nothing(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _nothing_type;
  _nothing_type nothing;





  typedef boost::shared_ptr< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SrvResetToPoseResponse_

typedef ::rovio::SrvResetToPoseResponse_<std::allocator<void> > SrvResetToPoseResponse;

typedef boost::shared_ptr< ::rovio::SrvResetToPoseResponse > SrvResetToPoseResponsePtr;
typedef boost::shared_ptr< ::rovio::SrvResetToPoseResponse const> SrvResetToPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rovio::SrvResetToPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rovio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a891d825193801ed1b6cde23b48a7ae";
  }

  static const char* value(const ::rovio::SrvResetToPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a891d825193801eULL;
  static const uint64_t static_value2 = 0xd1b6cde23b48a7aeULL;
};

template<class ContainerAllocator>
struct DataType< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rovio/SrvResetToPoseResponse";
  }

  static const char* value(const ::rovio::SrvResetToPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Empty nothing\n\
\n\
================================================================================\n\
MSG: std_msgs/Empty\n\
";
  }

  static const char* value(const ::rovio::SrvResetToPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nothing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvResetToPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rovio::SrvResetToPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rovio::SrvResetToPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "nothing: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.nothing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVIO_MESSAGE_SRVRESETTOPOSERESPONSE_H
