// Generated by gencpp from file rovio/SrvResetToPoseRequest.msg
// DO NOT EDIT!


#ifndef ROVIO_MESSAGE_SRVRESETTOPOSEREQUEST_H
#define ROVIO_MESSAGE_SRVRESETTOPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rovio
{
template <class ContainerAllocator>
struct SrvResetToPoseRequest_
{
  typedef SrvResetToPoseRequest_<ContainerAllocator> Type;

  SrvResetToPoseRequest_()
    : T_WM()  {
    }
  SrvResetToPoseRequest_(const ContainerAllocator& _alloc)
    : T_WM(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _T_WM_type;
  _T_WM_type T_WM;





  typedef boost::shared_ptr< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SrvResetToPoseRequest_

typedef ::rovio::SrvResetToPoseRequest_<std::allocator<void> > SrvResetToPoseRequest;

typedef boost::shared_ptr< ::rovio::SrvResetToPoseRequest > SrvResetToPoseRequestPtr;
typedef boost::shared_ptr< ::rovio::SrvResetToPoseRequest const> SrvResetToPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rovio::SrvResetToPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rovio

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e9e36137d6a9824420bd1d5101fe972";
  }

  static const char* value(const ::rovio::SrvResetToPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e9e36137d6a9824ULL;
  static const uint64_t static_value2 = 0x420bd1d5101fe972ULL;
};

template<class ContainerAllocator>
struct DataType< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rovio/SrvResetToPoseRequest";
  }

  static const char* value(const ::rovio::SrvResetToPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
geometry_msgs/Pose T_WM\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::rovio::SrvResetToPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.T_WM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrvResetToPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rovio::SrvResetToPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rovio::SrvResetToPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "T_WM: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.T_WM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVIO_MESSAGE_SRVRESETTOPOSEREQUEST_H
