// Generated by gencpp from file rovio/SrvResetToPose.msg
// DO NOT EDIT!


#ifndef ROVIO_MESSAGE_SRVRESETTOPOSE_H
#define ROVIO_MESSAGE_SRVRESETTOPOSE_H

#include <ros/service_traits.h>


#include <rovio/SrvResetToPoseRequest.h>
#include <rovio/SrvResetToPoseResponse.h>


namespace rovio
{

struct SrvResetToPose
{

typedef SrvResetToPoseRequest Request;
typedef SrvResetToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SrvResetToPose
} // namespace rovio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rovio::SrvResetToPose > {
  static const char* value()
  {
    return "a5cb619716a7f4c50b6ba2d44260ddcc";
  }

  static const char* value(const ::rovio::SrvResetToPose&) { return value(); }
};

template<>
struct DataType< ::rovio::SrvResetToPose > {
  static const char* value()
  {
    return "rovio/SrvResetToPose";
  }

  static const char* value(const ::rovio::SrvResetToPose&) { return value(); }
};


// service_traits::MD5Sum< ::rovio::SrvResetToPoseRequest> should match 
// service_traits::MD5Sum< ::rovio::SrvResetToPose > 
template<>
struct MD5Sum< ::rovio::SrvResetToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rovio::SrvResetToPose >::value();
  }
  static const char* value(const ::rovio::SrvResetToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rovio::SrvResetToPoseRequest> should match 
// service_traits::DataType< ::rovio::SrvResetToPose > 
template<>
struct DataType< ::rovio::SrvResetToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rovio::SrvResetToPose >::value();
  }
  static const char* value(const ::rovio::SrvResetToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rovio::SrvResetToPoseResponse> should match 
// service_traits::MD5Sum< ::rovio::SrvResetToPose > 
template<>
struct MD5Sum< ::rovio::SrvResetToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rovio::SrvResetToPose >::value();
  }
  static const char* value(const ::rovio::SrvResetToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rovio::SrvResetToPoseResponse> should match 
// service_traits::DataType< ::rovio::SrvResetToPose > 
template<>
struct DataType< ::rovio::SrvResetToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rovio::SrvResetToPose >::value();
  }
  static const char* value(const ::rovio::SrvResetToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVIO_MESSAGE_SRVRESETTOPOSE_H
